import fs from 'fs'
import path from 'path'

export type MonthlyFundReportInput = {
  language: 'en' | 'bn'
  month: number
  year: number
  fundBalance: number
  totalInvested: number
  totalCharity: number
  approvedMembers: number
  collectionsTrend: Array<{ monthLabel?: string; year?: number; approvedTotal?: number; pendingTotal?: number }>
  chairmanSignatureUrl?: string | null
  accountantSignatureUrl?: string | null
}

function bnDigits(input: string) {
  const map: Record<string, string> = {
    '0': '০', '1': '১', '2': '২', '3': '৩', '4': '৪',
    '5': '৫', '6': '৬', '7': '৭', '8': '৮', '9': '৯',
  }
  return input.replace(/[0-9]/g, (d) => map[d] || d)
}

function money(n: number, lang: 'en' | 'bn') {
  const s = `৳${Number(n || 0).toLocaleString()}`
  return lang === 'bn' ? bnDigits(s) : s
}

const PDF_TEXT = {
  en: {
    title: 'Monthly Fund Report',
    month: 'Month',
    fundBalance: 'Fund Balance',
    totalInvested: 'Total Invested',
    totalCharity: 'Total Charity',
    approvedMembers: 'Approved Members',
    lastSixMonths: 'Last 6 Months Collections',
    noData: 'No data available.',
    signature: 'Authorized Signature',
    footer: 'Generated by STEPS.',
  },
  bn: {
    title: 'মাসিক ফান্ড রিপোর্ট',
    month: 'মাস',
    fundBalance: 'ফান্ড ব্যালেন্স',
    totalInvested: 'মোট বিনিয়োগ',
    totalCharity: 'মোট দান',
    approvedMembers: 'অনুমোদিত সদস্য',
    lastSixMonths: 'শেষ ৬ মাসের সংগ্রহ',
    noData: 'কোনো ডাটা নেই।',
    signature: 'অনুমোদিত স্বাক্ষর',
    footer: 'STEPS দ্বারা তৈরি।',
  },
} as const

/**
 * Generate a PDF buffer (server-friendly) for the monthly fund report.
 */
export async function generateMonthlyFundReportPdfBuffer(input: MonthlyFundReportInput) {
  // Dynamically import heavy PDF library only when this function is called
  const { jsPDF } = await import('jspdf')

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const margin = 40

  const lang = input.language === 'bn' ? 'bn' : 'en'
  const T = PDF_TEXT[lang]
  const v = (s: string) => (lang === 'bn' ? bnDigits(s) : s)

  // Logo
  try {
    const logoPath = path.join(process.cwd(), 'public', 'logo-dark.png')
    const buf = fs.readFileSync(logoPath)
    doc.addImage(`data:image/png;base64,${buf.toString('base64')}`, 'PNG', margin, 28, 70, 70)
  } catch {}

  // Seal watermark
  try {
    const sealPath = path.join(process.cwd(), 'public', 'assets', 'fund-seal.png')
    const buf = fs.readFileSync(sealPath)
    const img = `data:image/png;base64,${buf.toString('base64')}`
    const GState = (doc as any).GState
    if (GState) (doc as any).setGState(new GState({ opacity: 0.08 }))
    const size = Math.min(pageW, pageH) * 0.55
    doc.addImage(img, 'PNG', (pageW - size) / 2, (pageH - size) / 2, size, size)
    if (GState) (doc as any).setGState(new GState({ opacity: 1 }))
  } catch {}

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('STEPS', pageW / 2, 52, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.text(T.title, pageW / 2, 72, { align: 'center' })

  doc.setFontSize(11)
  doc.text(`${T.month}: ${v(`${input.month}/${input.year}`)}`, margin, 115)

  let y = 140
  const row = (label: string, value: string) => {
    doc.text(`${label}: ${value}`, margin, y)
    y += 16
  }

  row(T.fundBalance, money(input.fundBalance, lang))
  row(T.totalInvested, money(input.totalInvested, lang))
  row(T.totalCharity, money(input.totalCharity, lang))
  row(T.approvedMembers, v(String(input.approvedMembers)))

  y += 10
  doc.setFont('helvetica', 'bold')
  doc.text(T.lastSixMonths, margin, y)
  doc.setFont('helvetica', 'normal')
  y += 16

  const items = (input.collectionsTrend || []).slice(-6)
  if (!items.length) {
    doc.setTextColor(100)
    doc.text(T.noData, margin, y)
    doc.setTextColor(0)
  } else {
    for (const m of items) {
      const label = `${m.monthLabel || ''} ${m.year || ''}`.trim()
      const val = money(Number(m.approvedTotal || 0), lang)
      doc.text(`${label}: ${val}`, margin, y)
      y += 14
    }
  }

  // Signatures
  const sigY = 720
  doc.setDrawColor(160)
  doc.line(margin, sigY, margin + 200, sigY)
  doc.line(pageW - margin - 200, sigY, pageW - margin, sigY)

  doc.setFontSize(10)
  doc.text(T.signature, margin + 100, sigY + 14, { align: 'center' })
  doc.text(T.signature, pageW - margin - 100, sigY + 14, { align: 'center' })

  const tryAddSig = (dataUrl: string | null | undefined, x: number) => {
    if (!dataUrl) return
    try {
      const fmt = dataUrl.includes('image/jpeg') || dataUrl.includes('image/jpg') ? 'JPEG' : 'PNG'
      doc.addImage(dataUrl, fmt as any, x, sigY - 55, 160, 50)
    } catch {}
  }

  tryAddSig(input.chairmanSignatureUrl, margin + 20)
  tryAddSig(input.accountantSignatureUrl, pageW - margin - 180)

  doc.setFontSize(9)
  doc.setTextColor(100)
  doc.text(T.footer, pageW / 2, 810, { align: 'center' })
  doc.setTextColor(0)

  const arrayBuf = doc.output('arraybuffer')
  return Buffer.from(arrayBuf)
}

/**
 * Client helper: generate + immediately download.
 */
export async function generateMonthlyFundReportPdf(input: MonthlyFundReportInput) {
  const buf = await generateMonthlyFundReportPdfBuffer(input)
  const blob = new Blob([buf], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `monthly-report-${input.year}-${input.month}.pdf`
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}