-- =========================
-- CORE USER & PROFILE SYSTEM
-- =========================

create table public.profiles (
  id uuid not null,
  full_name text null,
  phone text null,
  email text null,
  role public.app_role not null default 'member'::app_role,
  approved boolean not null default false,
  suspended boolean not null default false,
  banned boolean not null default false,
  photo_url text null,
  bio text null,
  signature_url text null,
  chairman_signature_url text null,
  accountant_signature_url text null,
  profile_completed boolean not null default false,
  kyc_status text null,
  nid_number text null,
  nid_front_url text null,
  nid_back_url text null,
  current_institution text null,
  current_subject text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  signature_data_url text null,
  signature_updated_at timestamp with time zone null,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
);

-- =========================
-- CONTRIBUTIONS SYSTEM
-- =========================

create table public.contributions (
  id uuid not null default gen_random_uuid (),
  invoice_no bigint generated by default as identity not null,
  user_id uuid not null,
  year integer not null,
  month integer not null,
  amount numeric(12, 2) not null,
  fines_amount numeric(12, 2) not null default 0,
  total_amount numeric GENERATED ALWAYS as ((amount + fines_amount)) STORED,
  payment_method text not null,
  status public.approval_status not null default 'pending',
  submitted_at timestamp with time zone not null default now(),
  approved_at timestamp with time zone null,
  approved_by uuid null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint contributions_pkey primary key (id)
);

-- =========================
-- EXPENSE SYSTEM
-- =========================

create table public.expenses (
  id uuid not null default gen_random_uuid (),
  title text not null,
  amount numeric(14, 2) not null,
  note text null,
  expense_date date null,
  covered boolean not null default false,
  status public.expense_status not null default 'uncovered',
  covered_at timestamp with time zone null,
  covered_by uuid null,
  reimbursed_amount numeric null default 0,
  member_id uuid null,
  paid_by uuid null,
  type text null default 'general',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint expenses_pkey primary key (id)
);

-- =========================
-- EXPENSE TRACKING
-- =========================

create table public.expense_logs (
  id uuid not null default gen_random_uuid (),
  expense_id uuid null,
  admin_id uuid null,
  amount numeric null,
  created_at timestamp default now(),
  constraint expense_logs_pkey primary key (id)
);

create table public.expense_reimbursements (
  id uuid not null default gen_random_uuid (),
  expense_id uuid null,
  admin_id uuid null,
  amount numeric null,
  created_at timestamp default now(),
  constraint expense_reimbursements_pkey primary key (id)
);

-- =========================
-- PROFIT DISTRIBUTION
-- =========================

create table public.profit_distributions (
  id uuid not null default gen_random_uuid (),
  title text not null,
  total_profit numeric(14, 2) not null default 0,
  profit_amount numeric(12, 2) not null default 0,
  source_type text null,
  investment_id uuid null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint profit_distributions_pkey primary key (id)
);

create table public.profit_distribution_items (
  id uuid not null default gen_random_uuid (),
  profit_distribution_id uuid not null,
  user_id uuid not null,
  amount numeric(14, 2) not null default 0,
  basis_note text null,
  created_at timestamp with time zone not null default now(),
  constraint profit_distribution_items_pkey primary key (id)
);

-- =========================
-- LOAN SYSTEM
-- =========================

create table public.loan_applications (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  amount numeric(12, 2) not null,
  status public.loan_status not null default 'pending',
  approved_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint loan_applications_pkey primary key (id)
);

-- =========================
-- CHARITY SYSTEM (HARAM FLOW)
-- =========================

create table public.charity_pool (
  id uuid not null default gen_random_uuid (),
  total_bank_interest numeric(14, 2) not null default 0,
  total_available_for_charity numeric(14, 2) not null default 0,
  total_charity_pool numeric(14, 2) not null default 0,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint charity_pool_pkey primary key (id)
);

create table public.charity_records (
  id uuid not null default gen_random_uuid (),
  title text,
  amount numeric(14, 2) not null default 0,
  record_type text not null default 'outflow',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint charity_records_pkey primary key (id)
);

-- =========================
-- SYSTEM SETTINGS
-- =========================

create table public.app_settings (
  key text not null,
  value jsonb not null default '{}',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint app_settings_pkey primary key (key)
);

create table public.system_settings (
  id uuid not null default gen_random_uuid (),
  key text unique,
  value text,
  constraint system_settings_pkey primary key (id)
);

-- =========================
-- ACTIVITY & LOGGING
-- =========================

create table public.activity_events (
  id uuid not null default gen_random_uuid (),
  user_id uuid null,
  event_name text not null,
  payload jsonb not null default '{}',
  created_at timestamp with time zone not null default now(),
  constraint activity_events_pkey primary key (id)
);

create table public.audit_logs (
  id uuid not null default gen_random_uuid (),
  actor_id uuid null,
  action text not null,
  entity_type text not null,
  entity_id uuid null,
  meta jsonb not null default '{}',
  created_at timestamp with time zone not null default now(),
  constraint audit_logs_pkey primary key (id)
);

-- =========================
-- CERTIFICATE SYSTEM
-- =========================

create table public.certificates (
  id uuid not null default gen_random_uuid (),
  certificate_id text not null,
  recipient_name text not null,
  certificate_type text not null,
  issue_date date not null default CURRENT_DATE,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint certificates_pkey primary key (id)
);

create table public.certificate_events (
  id uuid not null default gen_random_uuid (),
  certificate_row_id uuid not null,
  action text not null,
  created_at timestamp with time zone not null default now(),
  constraint certificate_events_pkey primary key (id)
);

-- =========================
-- NOTIFICATIONS & MESSAGES
-- =========================

create table public.announcements (
  id uuid not null default gen_random_uuid (),
  title text not null,
  body text not null,
  target text not null default 'all',
  created_at timestamp with time zone not null default now(),
  constraint announcements_pkey primary key (id)
);

create table public.chairman_messages (
  id uuid not null default gen_random_uuid (),
  title text not null,
  body text not null,
  created_at timestamp with time zone not null default now(),
  constraint chairman_messages_pkey primary key (id)
);